---
title: "Audrey_Zhu_Ying_Xiong_pqhs431_projectA_report"
author: "Audrey Zhu and Ying Xiong"
date: "`r Sys.Date()"
output: 
  rmdformats::readthedown:
    highlight: kate
    number_sections: TRUE
---
# Preliminaries

```{r setup, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)

options(max.print="100")
opts_chunk$set(comment=NA)
opts_knit$set(width=75)
```

## R Packages

```{r load_packages}
library(glue)
library(janitor)
library(car)
library(equatiomatic)
library(broom)
library(patchwork)
library(ggrepel)
library(tidyverse)
```

## Data Ingest

```{r ingest_data}
chr <- readRDS("data/chr_2021_Audrey_Zhu_Ying_Xiong.Rds")
```

# Analysis 1

```{r a1_variables}
naniar::miss_var_summary(chr %>% 
                           select(county, median_household_income,
                                  some_college))

chr %>% filter(county == "Cuyahoga County") %>% 
  select()
```


```{r a1_scatterplot}
ggplot(chr, aes(x = some_college, y = median_household_income)) +
  geom_point(col = "lightslateblue", alpha = 0.7) +
  geom_smooth(method = loess, se = FALSE) +
  geom_smooth(method = lm, se = FALSE, col = "red") +
  geom_label(x = 30, y = 100, size = 3,
             label = glue('Pearson r = {round_half_up(cor(chr$some_college, 
                          chr$median_household_income), 3)}.')) +
  theme_bw() +
  labs(title = "Some College vs. Median Household Income",
       x = "Percent of Adult Population with Some College Education",
       y = "Median Household Income (thousands of dollars)")
```

## Box-Cox Analysis

```{r a1_boxcox}
boxCox(chr$median_household_income ~ chr$some_college)
```

## Inverse Transformation

```{r a1_transformed_scatter}
a1_inv <- chr %>% 
  mutate(inv_median_household_income = 1/median_household_income)

ggplot(a1_inv, aes(x = some_college, y = inv_median_household_income)) +
  geom_point(col = "lightslateblue", alpha = 0.7) +
  geom_smooth(method = loess, se = FALSE) +
  geom_smooth(method = lm, se = FALSE, col = "red") +
  theme_bw() +
  labs(title = "Inverse Transformation of Some College vs. Median Household Income",
       x = "Percent of Adult Population with Some College Education",
       y = "Inverse of Median Household Income")
```

## Fitted Model

```{r a1_lm}
model1 <- lm(inv_median_household_income ~ some_college, data = a1_inv)

model1

extract_eq(model1, use_coefs = TRUE, coef_digits = 5)
```

```{r a1_model_summary}
tidy(model1, conf.int = TRUE, conf.level = 0.90) %>%
  select(term, estimate, std.error, conf.low, conf.high) %>% kable()

glance(model1) %>% select(nobs, r.squared, sigma) %>% kable()

cor(a1_inv$some_college, a1_inv$inv_median_household_income)
```

## Residuals Analysis

```{r a1_residuals}
a1_aug <- augment(model1, data = a1_inv)

p1 <- ggplot(a1_aug, aes(x = .fitted, y = .resid)) +
  geom_point(col = "lightslateblue") +
  geom_smooth(method = "lm", se = FALSE, col = "red") +
  geom_smooth(method = "loess", se = FALSE, col = "blue") +
  theme_bw() +
  labs(title = "Linearity of Model1 Residuals")

p2 <- ggplot(a1_aug, aes(sample = .resid)) +
  geom_qq(col = "lightslateblue") + geom_qq_line(col = "black") +
  theme(aspect.ratio = 1) +
  labs(title = "Normal Q-Q: Model1 Residuals",
       y = "Inverse of Median Household Income") +
  theme_bw()

p1 + p2 + plot_layout(widths = c(1,1))
```

### Cuyahoga County Prediction

```{r a1_cuyahoga}
1/predict(model1, chr %>% filter(county == "Cuyahoga County"))

chr %>% 
  filter(county == "Cuyahoga County") %>% select(county, median_household_income)
```

### Two Counties with the Largest Residuals

```{r a1_largest_residuals}
a1_aug %>% slice_max(abs(.resid), n = 2) %>% 
  select(state, county, median_household_income, some_college, .resid)
```

# Analysis 2

```{r a2_variables}
naniar::miss_var_summary(chr %>% 
                           select(state, median_household_income,
                                  long_commute_5cat))

chr %>% filter(county == "Cuyahoga County") %>% 
  select(county, median_household_income, long_commute_5cat)
```


```{r a2_boxplots}
ggplot(chr, aes(x = median_household_income, y = long_commute_5cat, 
                fill = long_commute_5cat)) +
  geom_boxplot() +
  guides(fill = "none") +
  theme_bw() +
  labs(x = "Median Household Income (thousands of dollars)",
       y = "Percentage of Lone Commuters 
       with a Long Commute",
       title = "Distribution of Median Household Income by Commute Category")
```

### Inverse Transformation

```{r a2_inv}
a2_inv <- chr %>% 
  mutate(inv_median_household_income = 1/median_household_income)

ggplot(a2_inv, aes(x = inv_median_household_income, y = long_commute_5cat, 
                fill = long_commute_5cat)) +
  geom_boxplot() +
  guides(fill = "none") +
  theme_bw() +
  labs(x = "Inverse of Median Household Income",
       y = "Percentage of Lone Commuters 
       with a Long Commute",
       title = "Inverse Transformation of Median Household Income")
```

## Fitted Model

```{r model2}
model2 <- lm(inv_median_household_income ~ long_commute_5cat, data = a2_inv)

model2

extract_eq(model2, use_coefs = TRUE, coef_digits = 5)
```

```{r a2_model_summary}
tidy(model2, conf.int = TRUE, conf.level = 0.90) %>%
  select(term, estimate, std.error, conf.low, conf.high) %>% kable()

glance(model2) %>% select(nobs, r.squared, sigma) %>% kable()
```

## Prediction Analysis

```{r a2_residuals}
a2_aug <- augment(model2, data = a2_inv)

ggplot(a2_aug, aes(x = .resid, y = long_commute_5cat, 
                   fill = long_commute_5cat)) +
  geom_boxplot() +
  guides(fill = "none") +
  theme_bw() +
  labs(title = "Distribution of Residuals by Commute Category",
       x = "Residuals",
       y = "Commute Category")

ggplot(a2_aug, aes(sample = .resid, col = long_commute_5cat)) +
  geom_qq() +
  geom_qq_line(col = "black") +
  facet_wrap(~ long_commute_5cat) +
  guides(col = "none") +
  theme_bw() +
  labs(title = "Normality of Residual Distribution by Commute Category")
```

```{r a2_cuyahoga}
1/predict(model2, chr %>% filter(county == "Cuyahoga County"))

chr %>% filter(county == "Cuyahoga County") %>% 
  select(state, county, median_household_income, long_commute_5cat)
```

```{r a2_largest_residuals}
a2_aug %>% slice_max(abs(.resid), n = 2) %>% 
  select(state, county, median_household_income, long_commute_5cat, .resid)
```